package com.blz.gundam_database.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MAIN_LIST_BY_WORK_ENTITY".
 */
public class MainListByWorkEntity {

    private String workId;
    private String name;
    private String originalName;
    private String englishName;
    private String storyYear;
    private String icon;

    public MainListByWorkEntity() {
    }

    public MainListByWorkEntity(String workId, String name, String originalName, String englishName, String storyYear, String icon) {
        this.workId = workId;
        this.name = name;
        this.originalName = originalName;
        this.englishName = englishName;
        this.storyYear = storyYear;
        this.icon = icon;
    }

    public String getWorkId() {
        return workId;
    }

    public void setWorkId(String workId) {
        this.workId = workId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getOriginalName() {
        return originalName;
    }

    public void setOriginalName(String originalName) {
        this.originalName = originalName;
    }

    public String getEnglishName() {
        return englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getStoryYear() {
        return storyYear;
    }

    public void setStoryYear(String storyYear) {
        this.storyYear = storyYear;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

}
