package com.blz.gundam_database.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "MOBILE_SUIT_ENTITY".
 */
public class MobileSuitEntity implements Serializable{

    private String objectId;
    private String workId;
    private String originalName;
    private String modelSeries;
    private String scale;
    private String itemNo;
    private String launchDate;
    private String price;
    private String images;
    private String headImage;
    private String version;
    private String manufacturer;
    private String prototypeMaster;
    private String boxImage;
    private String llType;//1代表竖版 2代表横版

    public MobileSuitEntity() {
    }

    public MobileSuitEntity(String objectId) {
        this.objectId = objectId;
    }

    public MobileSuitEntity(String objectId, String workId, String originalName, String modelSeries, String scale, String itemNo, String launchDate, String price, String images, String headImage, String version, String manufacturer, String prototypeMaster, String boxImage, String llType) {
        this.objectId = objectId;
        this.workId = workId;
        this.originalName = originalName;
        this.modelSeries = modelSeries;
        this.scale = scale;
        this.itemNo = itemNo;
        this.launchDate = launchDate;
        this.price = price;
        this.images = images;
        this.headImage = headImage;
        this.version = version;
        this.manufacturer = manufacturer;
        this.prototypeMaster = prototypeMaster;
        this.boxImage = boxImage;
        this.llType = llType;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    public String getWorkId() {
        return workId;
    }

    public void setWorkId(String workId) {
        this.workId = workId;
    }

    public String getOriginalName() {
        return originalName;
    }

    public void setOriginalName(String originalName) {
        this.originalName = originalName;
    }

    public String getModelSeries() {
        return modelSeries;
    }

    public void setModelSeries(String modelSeries) {
        this.modelSeries = modelSeries;
    }

    public String getScale() {
        return scale;
    }

    public void setScale(String scale) {
        this.scale = scale;
    }

    public String getItemNo() {
        return itemNo;
    }

    public void setItemNo(String itemNo) {
        this.itemNo = itemNo;
    }

    public String getLaunchDate() {
        return launchDate;
    }

    public void setLaunchDate(String launchDate) {
        this.launchDate = launchDate;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getImages() {
        return images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    public String getHeadImage() {
        return headImage;
    }

    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getPrototypeMaster() {
        return prototypeMaster;
    }

    public void setPrototypeMaster(String prototypeMaster) {
        this.prototypeMaster = prototypeMaster;
    }

    public String getBoxImage() {
        return boxImage;
    }

    public void setBoxImage(String boxImage) {
        this.boxImage = boxImage;
    }

    public String getLlType() {
        return llType;
    }

    public void setLlType(String llType) {
        this.llType = llType;
    }

}
