package com.blz.gundam_database.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "SPLASH_SCREEN_ENTITY".
 */
public class SplashScreenEntity {

    private String imgUrl;

    public SplashScreenEntity() {
    }

    public SplashScreenEntity(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

}
