package com.blz.gundam_database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.blz.gundam_database.entities.SplashScreenEntity;

import com.blz.gundam_database.dao.SplashScreenEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig splashScreenEntityDaoConfig;

    private final SplashScreenEntityDao splashScreenEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        splashScreenEntityDaoConfig = daoConfigMap.get(SplashScreenEntityDao.class).clone();
        splashScreenEntityDaoConfig.initIdentityScope(type);

        splashScreenEntityDao = new SplashScreenEntityDao(splashScreenEntityDaoConfig, this);

        registerDao(SplashScreenEntity.class, splashScreenEntityDao);
    }
    
    public void clear() {
        splashScreenEntityDaoConfig.getIdentityScope().clear();
    }

    public SplashScreenEntityDao getSplashScreenEntityDao() {
        return splashScreenEntityDao;
    }

}
